flowchart TD
    infra["WebApplicationFactory
    (IntegrationTest + InMemory + Seed)"]

    subgraph Unitarios
        u1[ResponseServiceTests]
        u2["QuestionariosApiClientTests"]
        u3["SurveyControllerTests
            WebPublico"]
    end

    subgraph Integracao
        i1["SurveyControllerTests
            (API GET /survey/{id})"]
        
        i2["ResponsesControllerTests 
        (API POST /responses)"]
        
        i3["ResultsControllerTests 
        (API GET /results/{id}/chart)"]
    end

    u1 --> infra
    u2 --> infra
    u3 --> infra
    i1 --> infra
    i2 --> infra
    i3 --> infra
